#!/bin/bash

# 1. Detect the Connected Screen
INTERNAL=$(xrandr --query | grep " connected" | grep -v "HDMI" | head -n1 | cut -d" " -f1)

if [ -z "$INTERNAL" ]; then
    INTERNAL=$(xrandr --query | grep " connected" | head -n1 | cut -d" " -f1)
fi

# 2. Fix Resolution (The None-1 Fix)
if [[ "$INTERNAL" == *"None"* ]]; then
    xrandr --newmode "1920x1080_144.00"  452.50  1920 2088 2296 2672  1080 1083 1088 1177 -hsync +vsync
    xrandr --addmode $INTERNAL "1920x1080_144.00"
    xrandr --output $INTERNAL --primary --mode "1920x1080_144.00"
else
    xrandr --output $INTERNAL --primary --auto
fi


# --- CONFLICT FIX 1: REMOVED wal -R ---
# We removed 'wal -R' because it overrides the new colors generated by your switcher.

# --- CONFLICT FIX 2: DOUBLE-CHECK POLYBAR ---
# Wait and double-check to avoid flickering during i3 reload

if ! pgrep -x "polybar" >/dev/null; then
    # Wait briefly and check again (i3 reload in progress?)
    sleep 0.3
    if ! pgrep -x "polybar" >/dev/null; then
        export MONITOR=$INTERNAL
        
        # Launch your 6 bars
        for bar in main pam2 pam6 pam3 pam4 pam5; do
            polybar -q $bar -c ~/.config/polybar/pamela/config.ini &
        done
    fi
fi

# 4. Enforce Gaps (Always run this to be safe)
sleep 1
i3-msg gaps top all set 45
